---
new_page_extension: md
auto_deploy: true
admin_path: http://howrahrun.netlify.com
webhook_url: 
sections: 
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.31.1
